export const TRACKED_UIDS = [

    { uid: '60d08b15d142afee4b1dfabe', label: 'DYGS'   },
    { uid: '652fe93abfea717754b98d1b', label: 'Best'   },
    { uid: '63d04d93d142afb3369576af', label: 'RyGuy' },
    { uid: '6342686bbfea71de1d553d19', label: 'Hiru'     },
    { uid: '6449c8acd142afb66d07f776', label: 'Invis'     },
    { uid: '62a4f957d142afdd4f5f41e9', label: 'Tarkin'   },
// { uid: 'REPLACE_WITH_REAL_UID_4', label: 'Player Four'    },
// { uid: 'REPLACE_WITH_REAL_UID_5', label: 'Player Five'    },
// { uid: 'REPLACE_WITH_REAL_UID_6', label: 'Player Six'     },
// { uid: 'REPLACE_WITH_REAL_UID_7', label: 'Player Seven'   },
// { uid: 'REPLACE_WITH_REAL_UID_8', label: 'Player Eight'   },
// { uid: 'REPLACE_WITH_REAL_UID_9', label: 'Player Nine'    },
// { uid: 'REPLACE_WITH_REAL_UID_10', label: 'Player Ten'    },
// { uid: 'REPLACE_WITH_REAL_UID_11', label: 'Player Eleven' },
// { uid: 'REPLACE_WITH_REAL_UID_12', label: 'Player Twelve' },
// { uid: 'REPLACE_WITH_REAL_UID_13', label: 'Player Thirteen' },
// { uid: 'REPLACE_WITH_REAL_UID_14', label: 'Player Fourteen' },
// { uid: 'REPLACE_WITH_REAL_UID_15', label: 'Player Fifteen' },
// { uid: 'REPLACE_WITH_REAL_UID_16', label: 'Player Sixteen' },
// { uid: 'REPLACE_WITH_REAL_UID_17', label: 'Player Seventeen' },
// { uid: 'REPLACE_WITH_REAL_UID_18', label: 'Player Eighteen' },
// { uid: 'REPLACE_WITH_REAL_UID_19', label: 'Player Nineteen' },
// { uid: 'REPLACE_WITH_REAL_UID_20', label: 'Player Twenty' },
// { uid: 'REPLACE_WITH_REAL_UID_21', label: 'Player Twenty-One' },
// { uid: 'REPLACE_WITH_REAL_UID_22', label: 'Player Twenty-Two' },
// { uid: 'REPLACE_WITH_REAL_UID_23', label: 'Player Twenty-Three' },
// { uid: 'REPLACE_WITH_REAL_UID_24', label: 'Player Twenty-Four' },
// { uid: 'REPLACE_WITH_REAL_UID_25', label: 'Player Twenty-Five' },
// { uid: 'REPLACE_WITH_REAL_UID_26', label: 'Player Twenty-Six' },
// { uid: 'REPLACE_WITH_REAL_UID_27', label: 'Player Twenty-Seven' },
// { uid: 'REPLACE_WITH_REAL_UID_28', label: 'Player Twenty-Eight' },
// { uid: 'REPLACE_WITH_REAL_UID_29', label: 'Player Twenty-Nine' },
// { uid: 'REPLACE_WITH_REAL_UID_30', label: 'Player Thirty' },
// { uid: 'REPLACE_WITH_REAL_UID_31', label: 'Player Thirty-One' },
// { uid: 'REPLACE_WITH_REAL_UID_32', label: 'Player Thirty-Two' },
// { uid: 'REPLACE_WITH_REAL_UID_33', label: 'Player Thirty-Three' },
// { uid: 'REPLACE_WITH_REAL_UID_34', label: 'Player Thirty-Four' },
// { uid: 'REPLACE_WITH_REAL_UID_35', label: 'Player Thirty-Five' },
// { uid: 'REPLACE_WITH_REAL_UID_36', label: 'Player Thirty-Six' },
// { uid: 'REPLACE_WITH_REAL_UID_37', label: 'Player Thirty-Seven' },
// { uid: 'REPLACE_WITH_REAL_UID_38', label: 'Player Thirty-Eight' },
// { uid: 'REPLACE_WITH_REAL_UID_39', label: 'Player Thirty-Nine' },
// { uid: 'REPLACE_WITH_REAL_UID_40', label: 'Player Forty' },
// { uid: 'REPLACE_WITH_REAL_UID_41', label: 'Player Forty-One' },
// { uid: 'REPLACE_WITH_REAL_UID_42', label: 'Player Forty-Two' },
// { uid: 'REPLACE_WITH_REAL_UID_43', label: 'Player Forty-Three' },
// { uid: 'REPLACE_WITH_REAL_UID_44', label: 'Player Forty-Four' },
// { uid: 'REPLACE_WITH_REAL_UID_45', label: 'Player Forty-Five' },
// { uid: 'REPLACE_WITH_REAL_UID_46', label: 'Player Forty-Six' },
// { uid: 'REPLACE_WITH_REAL_UID_47', label: 'Player Forty-Seven' },
// { uid: 'REPLACE_WITH_REAL_UID_48', label: 'Player Forty-Eight' },
// { uid: 'REPLACE_WITH_REAL_UID_49', label: 'Player Forty-Nine' },
// { uid: 'REPLACE_WITH_REAL_UID_50', label: 'Player Fifty' },
// { uid: 'REPLACE_WITH_REAL_UID_51', label: 'Player Fifty-One' },
// { uid: 'REPLACE_WITH_REAL_UID_52', label: 'Player Fifty-Two' },
// { uid: 'REPLACE_WITH_REAL_UID_53', label: 'Player Fifty-Three' },
// { uid: 'REPLACE_WITH_REAL_UID_54', label: 'Player Fifty-Four' },
// { uid: 'REPLACE_WITH_REAL_UID_55', label: 'Player Fifty-Five' },
// { uid: 'REPLACE_WITH_REAL_UID_56', label: 'Player Fifty-Six' },
// { uid: 'REPLACE_WITH_REAL_UID_57', label: 'Player Fifty-Seven' },
// { uid: 'REPLACE_WITH_REAL_UID_58', label: 'Player Fifty-Eight' },
// { uid: 'REPLACE_WITH_REAL_UID_59', label: 'Player Fifty-Nine' },
// { uid: 'REPLACE_WITH_REAL_UID_60', label: 'Player Sixty' },
// { uid: 'REPLACE_WITH_REAL_UID_61', label: 'Player Sixty-One' },
// { uid: 'REPLACE_WITH_REAL_UID_62', label: 'Player Sixty-Two' },
// { uid: 'REPLACE_WITH_REAL_UID_63', label: 'Player Sixty-Three' },
// { uid: 'REPLACE_WITH_REAL_UID_64', label: 'Player Sixty-Four' },
// { uid: 'REPLACE_WITH_REAL_UID_65', label: 'Player Sixty-Five' },
// { uid: 'REPLACE_WITH_REAL_UID_66', label: 'Player Sixty-Six' },
// { uid: 'REPLACE_WITH_REAL_UID_67', label: 'Player Sixty-Seven' }
];
