name: Track Player Count

on:
  schedule:
    # Runs every 15 minutes (UTC)
    - cron: '*/15 * * * *'
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3️⃣ Cache Node modules (optional)
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install || echo "No dependencies to install"

      # 5️⃣ Run the player count fetch
      - name: Fetch player count
        run: |
          echo "Running fetch at UTC: $(date -u)"
          node fetch-player-count.js

      # 6️⃣ Commit and push the updated JSON
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add player-tracker-data.json
          git commit -m "Update player count data - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
